version: "1"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=stationSki stationSki
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
    volumes:
      - db:/var/lib/mysql

  spring_app:
    container_name: stationSki
    image: khouloudaskri/gestion-station-ski-1.0:latest
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
    volumes:
      - .m2:/root/.m2
    ports:
      - 8089:8089
    depends_on:
      - mysqldb