version: '3'
services :
  app:
    image: gestion-station-ski-1.0
    ports:
     - 8080:8080
    depends_on :
     - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: stationSki
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
          - 3306:3306 # Port d'écoute de MySQL